### ISSUE TITLE
Build problem with patch fragment after Tycho 3.0.0 update

### ISSUE THREAD

**Issue by phermsdorf** [eclipse-tycho/tycho#1408]
### Discussed in https://github.com/eclipse-tycho/tycho/discussions/1401

when building i see the following error on stderr in the build

```
[INFO] --- tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) @ ag.ion.noa ---
[INFO] Compiling 396 source files to /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/target/classes
Failed to init Classpath for jar file /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar
java.nio.file.NoSuchFileException: /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathMultiReleaseJar.initialize(ClasspathMultiReleaseJar.java:38)
	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
	at org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(JDTCompiler.java:385)
	at org.eclipse.tycho.compiler.jdt.JDTCompiler.performCompile(JDTCompiler.java:118)
	at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:414)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.doCompile(AbstractOsgiCompilerMojo.java:370)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:351)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```
in the next project the build fails with

`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-ds-plugin:3.0.0-SNAPSHOT:declarative-services (default-declarative-services) on project com.godyo.p4.office.ui: generation of ds components failed: A Jar can only accept a file or directory that exists: /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar -> [Help 1]`

Before we used Tycho 2.7.1 which worked with this setup.

Will try to create a reproducer ....

**Comment by laeubi** [comment]
Also if it might sound strange the first error is just a new warning from JDT and should not produce any issue, but the second one is the problem why the build fails but I htink that is quite easy to fix if we have an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue.

**Comment by phermsdorf** [comment]
Then maybe the patch fragment isn't the problem at all ... i had a similar error on a project which had no source folder but a project specific DS configuration (because all projects just have them) - after removing the DS configuration the error on that bundle was gone.
Don't know what the problem with this specific bundle is ... still setting up a IDE with a tycho workspace

**Comment by laeubi** [comment]
@phermsdorf you don't need a Tycho workspace, you can simply create a standalone maven example that reproduces the issue and then use that as the integrationtest project.

If it is too complex, I can offer to try a "blind" fix and you can check it with your real project by building a local version?

**Comment by laeubi** [comment]
@phermsdorf can you run maven with the `-e` switch and post the stack trace from the  `tycho-ds-plugin`?

**Comment by phermsdorf** [comment]
debug output:

```
[DEBUG] Original compiler output: 
[INFO] 
[INFO] --- tycho-ds-plugin:3.0.0-SNAPSHOT:declarative-services (default-declarative-services) @ com.godyo.p4.office.ui ---
[DEBUG] Configuring mojo org.eclipse.tycho:tycho-ds-plugin:3.0.0-SNAPSHOT:declarative-services from plugin realm ClassRealm[plugin>org.eclipse.tycho:tycho-ds-plugin:3.0.0-SNAPSHOT, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5cb0d902]
[DEBUG] Configuring mojo 'org.eclipse.tycho:tycho-ds-plugin:3.0.0-SNAPSHOT:declarative-services' with basic configurator -->
[DEBUG]   (f) classpath = true
[DEBUG]   (f) dsVersion = 1.3
[DEBUG]   (f) enabled = false
[DEBUG]   (f) path = OSGI-INF
[DEBUG]   (f) project = MavenProject: com.godyo.p4:com.godyo.p4.office.ui:5.0.2241-SNAPSHOT @ /home/peter/GODYO-P4-master4/git/P4/com.godyo.p4.office.ui/pom.xml
[DEBUG]   (f) skip = false
[DEBUG] -- end configuration --
[DEBUG] DS Plugin org.eclipse.tycho:tycho-ds-plugin has no useable configuration.
[DEBUG] declarative-services project configuration for MavenProject: com.godyo.p4:com.godyo.p4.office.ui:5.0.2241-SNAPSHOT @ /home/peter/GODYO-P4-master4/git/P4/com.godyo.p4.office.ui/pom.xml:
{path=OSGI-INF, generateBundleActivationPolicyLazy=true, eclipse.preferences.version=1, enabled=true, validationErrorLevel=error, validationErrorLevel.missingImplicitUnbindMethod=error}
[DEBUG] Project configuration for MavenProject: com.godyo.p4:com.godyo.p4.office.ui:5.0.2241-SNAPSHOT @ /home/peter/GODYO-P4-master4/git/P4/com.godyo.p4.office.ui/pom.xml: {path=OSGI-INF, generateBundleActivationPolicyLazy=true, eclipse.preferences.version=1, enabled=true, validationErrorLevel=error, validationErrorLevel.missingImplicitUnbindMethod=error}
```

<snip> and

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-ds-plugin:3.0.0-SNAPSHOT:declarative-services (default-declarative-services) on project com.godyo.p4.office.ui: generation of ds components failed: A Jar can only accept a file or directory that exists: /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-ds-plugin:3.0.0-SNAPSHOT:declarative-services (default-declarative-services) on project com.godyo.p4.office.ui: generation of ds components failed: A Jar can only accept a file or directory that exists: /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: generation of ds components failed: A Jar can only accept a file or directory that exists: /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar
	at org.eclipse.tycho.ds.DeclarativeServicesMojo.execute(DeclarativeServicesMojo.java:139)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
Caused by: java.lang.IllegalArgumentException: A Jar can only accept a file or directory that exists: /home/peter/GODYO-P4-master4/git/P4/com.godyo.p5.externlib.ag.ion.noa/patch.jar
	at aQute.bnd.osgi.Jar.<init>(Jar.java:141)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:237)
	at aQute.bnd.osgi.Analyzer.addClasspath(Analyzer.java:2560)
	at aQute.bnd.osgi.Analyzer.addClasspath(Analyzer.java:2549)
	at org.eclipse.tycho.ds.DeclarativeServicesMojo.execute(DeclarativeServicesMojo.java:115)
	... 22 more
```

**Comment by phermsdorf** [comment]
@laeubi 
I tried again but it still fails with the same error.
I think i saw a re-download of the tycho 3.0 snapshot bundles on the first run. Is there something else i need to do to get the latest tycho build?

**Comment by laeubi** [comment]
You need to use `-U` to force snapshot updates, beside this, as mentioned above, the JDT "Error" should not fail the build.

**Comment by phermsdorf** [comment]
@laeubi  Works for me. Thanks a lot for the fix!
