### ISSUE TITLE
better support justj

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#154]
The [documentation](https://www.eclipse.org/justj/?page=documentation) of justj contaisn severals hint/issues on configuration for tycho. We shoudl try to better support justj.

One example is that currently using justj requires to use `<resolveWithExecutionEnvironmentConstraints>false</resolveWithExecutionEnvironmentConstraints>` in some cases as tycho otherwhise fails to resolve some bundles/dependecies, also the explicit configuration of `<executionEnvironment>org.eclipse.justj.openjdk.hotspot.jre.full-15</executionEnvironment>` seems superflous. 

One can currently easyly break a build by simply reference justj as a repository...

**Comment by mickaelistria** [comment]
JustJ documentation is outdated, this was slightly improved in latest Tycho release.
See for example https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#executionEnvironment which does mention how to let resolution use JustJ simply by not injecting a particular EE; this is simpler to understand and more correct than using resolveWithExecutionEnvironmentConstraints=true (which will inject even more extra units to emulate the EE while one would typically want less)

**Comment by mickaelistria** [comment]
> In my particular case I was not able to make it work, as soon as I enable the <executionEnvironment>org.eclipse.justj.openjdk.hotspot.jre.full-15</executionEnvironment>

That's not what's in the doc (also doc might be unclear). For this to work, JustJ must be part of the resolved target platform, as a dependency of any form, and `<executionEnvironment>none</executionEnvironment>`.

> The main point here is, that I think we should somehow detect something like justj in the target and configure tycho somewhat automatic so "just it works" without much extra configuration.

That's a good idea; but not desired in the general case: if I'm building a random bundle and using in the TP a p2 repo that contains JustJ, it doesn't imply at all that JustJ should be the EE and should take priority over the EE that's deduced from the .target or MANIFEST.MF file. This should remain a user decision and setting, not something to automate.
It would IMO seem more interesting to detect this error case and improve the error message with a hint about how to troubleshot this particular case.
"Something like JustJ" => a unit that contains some capabilities with `osgi.ee` namespace.

**Comment by laeubi** [comment]
>  (also doc might be unclear)

at least to me obviously :-\

> if I'm building a random bundle and using in the TP a p2 repo that contains JustJ, it doesn't imply at all that JustJ should be the EE and should take priority over the EE that's deduced from the .target or MANIFEST.MF file

But that's what actually happens (and why I opened this ticket) as

> The JustJ JREs have explicit negative requirements to exclude a.jre and a.jre.javase from consideration during resolution

that leads in my case to a state where I was not able to build anyone once I include the justj as a repository (even though I just reference it in a product as a feature).

**Comment by mickaelistria** [comment]
OK, I now understand the issue about negative requirements.
Currently, the JustJ repo is only suitable when added to a repository/product module build; it's indeed causing issues for regular bundle/feature builds. I have not investigated further how this issue with the negative requirement can be removed; when we have a a.jre.unit defined by Tycho for dependency resolution and JustJ is not a dependency, I don't think we should see such error about justj making resolution fail.

**Comment by laeubi** [comment]
@mickaelistria I have created [an example](https://github.com/laeubi/tycho/commit/64fd84a25b9083c321ff431c9aa78e07dba5754b) that shows the problem.
If you build the project it will fail with
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: a.jre.javase 11.0.0
[ERROR]   Software being installed: product-with-justj-features 0.0.1
[ERROR]   Cannot satisfy dependency: org.eclipse.justj.openjdk.hotspot.jre.full 11.0.2.v20200815-0835 depends on: org.eclipse.equinox.p2.iu; a.jre.javase 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.justj.openjdk.hotspot.jre.full.feature.group 11.0.2.v20200815-0835 depends on: org.eclipse.equinox.p2.iu; org.eclipse.justj.openjdk.hotspot.jre.full [11.0.2.v20200815-0835,11.0.2.v20200815-0835]
[ERROR]   Cannot satisfy dependency: product-with-justj-features 0.0.1 depends on: org.eclipse.equinox.p2.iu; org.eclipse.justj.openjdk.hotspot.jre.full.feature.group 0.0.0
```
interestingly the build succeeds if one only uses a plugin based (just comment out the `<module>feature-product</module>`) but emits a warning
`[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from product-with-justj-bundles 0.0.1 to org.eclipse.equinox.p2.iu; org.eclipse.justj.openjdk.hotspot.jre.full [11.0.2.v20200815-0835,11.0.2.v20200815-0835].]`
that suggest that instead there is actually something wrong.

**Comment by laeubi** [comment]
What makes the build succeed in this case is adding
```
<plugin>
     <groupId>org.eclipse.tycho</groupId>
     <artifactId>target-platform-configuration</artifactId>
     <version>${tycho-version}</version>
     <configuration>
        <executionEnvironment>org.eclipse.justj.openjdk.hotspot.jre.full-11</executionEnvironment>
     </configuration>
  </plugin>
```
as suggested in the documentation. In a larger project I'm getting resolution errors with this configuration (I'm currently try to reproduce this as well).

Also as suggested I wonder if we could somehow "detect" the presence of such an ee in the target and maybe configure this by default?

**Comment by laeubi** [comment]
e.g. CustomEEResolutionHandler has checks to find a unit for the specified EE, so it seems possible to search for all units providing an EE and select the one that best fits.

**Comment by laeubi** [comment]
For the problematic dependency I get
> Missing requirement: com.github.haifengl.smile-core 1.5.3 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found

during the build (without justj everything works fine or if I disable `resolveWithExecutionEnvironmentConstraints`).

**Comment by laeubi** [comment]
Using `<executionEnvironment>none</executionEnvironment>` results in
```
[ERROR] Internal error: java.lang.IllegalStateException: Full specification of custom profile is not (yet) determined -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: Full specification of custom profile is not (yet) determined
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalStateException: Full specification of custom profile is not (yet) determined
	at org.eclipse.tycho.core.ee.ExecutionEnvironmentConfigurationImpl.getFullSpecification(ExecutionEnvironmentConfigurationImpl.java:131)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:272)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath(OsgiBundleProject.java:174)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:142)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0(TychoMavenLifecycleParticipant.java:127)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects(TychoMavenLifecycleParticipant.java:158)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:102)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:264)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 11 more
```

**Comment by HannesWell** [comment]
> 
> 
> What makes the build succeed in this case is adding
> 
> ```
> <plugin>
>      <groupId>org.eclipse.tycho</groupId>
>      <artifactId>target-platform-configuration</artifactId>
>      <version>${tycho-version}</version>
>      <configuration>
>         <executionEnvironment>org.eclipse.justj.openjdk.hotspot.jre.full-11</executionEnvironment>
>      </configuration>
>   </plugin>
> ```
> 
> as suggested in the documentation. In a larger project I'm getting resolution errors with this configuration (I'm currently try to reproduce this as well).
> 
> Also as suggested I wonder if we could somehow "detect" the presence of such an ee in the target and maybe configure this by default?

I recently integrated the JustJ-JRE 11 in our build where we build bundles, features and products together and everything worked fine when using only the quoted configuration mentioned by you. But this only worked with Tycho 2.3.0 and not before.

I reported it in the [JustJ form](https://www.eclipse.org/forums/index.php/t/1107858/), which lead to the latest update of the JustJ-doc.

In order to make it work, I had to debug Tycho (since the doc was not updated yet) and found the following classes as interesting parts:
- `org.eclipse.tycho.core.ee.ExecutionEnvironmentConfigurationImpl`
- `org.eclipse.tycho.core.osgitools.AbstractTychoProject#readExecutionEnvironmentConfiguration(ReactorProject, MavenSession,ExecutionEnvironmentConfiguration)`

Maybe this helps you in debugging for your problem.
Of course it would be even better if no special configuration would be possible.
I did not fully understand the concept of the `a.jre` yet but from what I read it is often causing problems and there are attempts/desires to remove it. Maybe this would help here too.

**Comment by mickaelistria** [comment]
> Using <executionEnvironment>none</executionEnvironment> results in [ERROR]

OK, this should be fixed. I'm looking at it.

**Comment by mickaelistria** [comment]
I found out that adding the EE unit to `rootIUs` in P2ResolverImpl.resolveDependencies() helps to silent the conflict between a.jre.javase and justj: with the rootIUs being an extra constraint, p2 knows what to do and doesn't face conflict. That helps for bundles.
But it has an opposite effect for products; those would still have to set `<executionEnvironment>none</executionEnvironment>` when using JustJ or they get polluted by irrelevant a.jre.javase stuff.

**Comment by laeubi** [comment]
> polluted by irrelevant a.jre.javase stuff

Thanks for the analysis, does this matter in any way?

**Comment by mickaelistria** [comment]
Having extra a.jre.javase in product doesn't matter as long as they're not required together with justj. Building a bundle and building a product have opposite expectations: the bundle should force isage of the a.jre.javase from EE by default to get justj ignored, while the product shouldn't force any EE ehen justj is required.

**Comment by laeubi** [comment]
I include justj as a feature in the products where it is relevan't should this include justj even though it is "ignored"?

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/tycho/pull/167 which shows a demo of how different projects play with JustJ. It looks like recent update to newer Equinox/p2 improved the situation enough so
* nothing particular is required for bundles (although it's likely JustJ units might be used in place of the expected a.jre.javase ones)
* modules that want to *include* justj (eg products) need to set `<executionEnvironment>none</executionEnvironment>` to avoid the a.jre.javase to leak in.

**Comment by laeubi** [comment]
> I found out that adding the EE unit to `rootIUs` in P2ResolverImpl.resolveDependencies() helps to silent the conflict between a.jre.javase and justj: with the rootIUs being an extra constraint, p2 knows what to do and doesn't face conflict. That helps for bundles.

@mickaelistria do you think we can add this change as a first step? Together with your example I think this is already a valuable improvement.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/tycho/pull/167/ is building fine on top of latest master; with just `<executionEnvironment>none</executionEnvironment>` for products that do include JustJ and without any change. I'm still unsure there is much we need to fix for the case of the bundle.
For the product, there is probably a way to get `<executionEnvironment>none</executionEnvironment>` not necessary.

**Comment by mickaelistria** [comment]
And let me repeat that "resolveWithExecutionEnvironmentConstraints" is a bad thing and should be avoided. I actually hope we can deprecate and remove this flag soon.

**Comment by laeubi** [comment]
> resolveWithExecutionEnvironmentConstraints" is a bad thing and should be avoided

Not using that option my build fails with:

```
[ERROR] Internal error: java.lang.IllegalStateException: Full specification of custom profile is not (yet) determined -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: Full specification of custom profile is not (yet) determined
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalStateException: Full specification of custom profile is not (yet) determined
	at org.eclipse.tycho.core.ee.ExecutionEnvironmentConfigurationImpl.getFullSpecification(ExecutionEnvironmentConfigurationImpl.java:131)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:325)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath(OsgiBundleProject.java:196)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:173)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0(TychoMavenLifecycleParticipant.java:127)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects(TychoMavenLifecycleParticipant.java:158)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:102)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:264)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 11 more
```

**Comment by mickaelistria** [comment]
Please add a test that shows this error.

**Comment by laeubi** [comment]
See my initial example and https://github.com/eclipse/tycho/issues/154#issuecomment-864813144 what should show the problem.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/tycho/pull/167 which includes your example and have things working fine.

**Comment by laeubi** [comment]
> See #167 which includes your example and have things working fine.

Well you asked for an example that reproduces the error (and it doesn't really help to reference a different/adjusted one where it work then...), so for completeness I created: https://github.com/eclipse/tycho/pull/174 that shows a common setup and fails with the given error...

Using `<executionEnvironment>none</executionEnvironment>` it fails
using `<resolveWithExecutionEnvironmentConstraints>false</resolveWithExecutionEnvironmentConstraints>` succeeds...

**Comment by mickaelistria** [comment]
As mentioned `<executionEnvironment>none</executionEnvironment>` should only be set for products at the moment. Nothing seems required for bundles, which actually are better using the a.jre.javase untils that match their EE better. So to improve JustJ support, we need to find a way for product resolution to not fail without this flag.
`<resolveWithExecutionEnvironmentConstraints>false</resolveWithExecutionEnvironmentConstraints>` should simply never ever be used.

**Comment by laeubi** [comment]
But still executionEnvironment=none should not result in obsure error or do I misunderstand something?

**Comment by laeubi** [comment]
has `executionEnvironment=none `any impact if jsutj is **not** used? Maybe one should simply behave as if none is set for every product (actually a product can't have an EE anyways....)

**Comment by mickaelistria** [comment]
> has executionEnvironment=none any impact if jsutj is not used?

Yes, this won't inject an unit to emulate the EE (a.jre.javase) and if no EE is already present in TP, it will make dependency resolution fails because of missing osgi.ee capabilities.

**Comment by laeubi** [comment]
@mickaelistria is your recent change to drop JREAction related here?

**Comment by mickaelistria** [comment]
> Is your recent change to drop JREAction related here?

I don't think so.

**Comment by bjmi** [comment]
After innumerous attempts to include a JustJ JRE 11 into a _product_ build I luckily found this https://www.eclipse.org/forums/index.php?t=msg&th=1106526&goto=1836594&#msg_1836594
> In the end, it's all kind of voodoo black magic, and all kind of frustrating.

The only working solution for me was: `org.eclipse.justj.buildtime=true`
```
<artifactId>target-platform-configuration</artifactId>
<configuration>
    <dependency-resolution>
        <profileProperties>
            <org.eclipse.justj.buildtime>true</org.eclipse.justj.buildtime>
        </profileProperties>
    </dependency-resolution>
</configuration>
```
None of following settings worked for me.
- `<executionEnvironment>org.eclipse.justj.openjdk.hotspot.jre.full-11</executionEnvironment>`
- `<filters><filter><type>p2-installable-unit</type><id>a.jre.javase</id><removeAll /></filter></filters>`

**Comment by laeubi** [comment]
"Did not work" is a bit vague can you explain the setup / problems your are encountered? Tycho include an example for a JustJ + product here: https://github.com/eclipse/tycho/tree/master/demo/justj/product

**Comment by bjmi** [comment]
Given:

1. Folder / module with Eclipse Target
**.target** platform file contains  
`<targetJRE path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11"/>`
2. Product folder / module
**pom.xml** contains
```
<repository>
    <id>justj</id>
    <url>https://download.eclipse.org/justj/jres/11/updates/release/latest/</url>
    <layout>p2</layout>
</repository>
```
**.product** file contains
```
<features>
    ...
    <feature id="org.eclipse.justj.openjdk.hotspot.jre.full" installMode="root"/>
</features>
```

Building the whole reactor (bundles, features, target, product) fails very early when resolving dependencies and finally ends up with
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: a.jre.javase 11.0.0
[ERROR]   Software being installed: acme.product 1.0.0.qualifier
[ERROR]   Cannot satisfy dependency: acme.product 1.0.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.justj.openjdk.hotspot.jre.full.feature.group 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.justj.openjdk.hotspot.jre.full 11.0.14.v20220201-1322 conflicts with: org.eclipse.equinox.p2.iu; a.jre.javase 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.justj.openjdk.hotspot.jre.full.feature.group 11.0.14.v20220201-1322 depends on: org.eclipse.equinox.p2.iu; org.eclipse.justj.openjdk.hotspot.jre.full [11.0.14.v20220201-1322,11.0.14.v20220201-1322]
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
```

**Comment by laeubi** [comment]
@bjmi if you still see issues with 3.0.0 release pleas open a new issue with your problem at best provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue.
