### ISSUE TITLE
Maven Loockup can become really slow and should cache previous requests

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-tycho/tycho#1969]
https://ci.eclipse.org/tycho/job/tycho-github/job/master/38/console

```
ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 435.657 s <<< FAILURE! - in org.eclipse.tycho.test.packaging.ConsumerPomTest
[ERROR] org.eclipse.tycho.test.packaging.ConsumerPomTest.testReplaceP2  Time elapsed: 435.652 s  <<< FAILURE!
java.lang.AssertionError: dependency with groupId=org.eclipse.platform and artifactId=org.eclipse.equinox.preferences not found in [Dependency {groupId=org.osgi, artifactId=org.osgi.service.prefs, version=1.1.2, type=jar}]
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.tycho.test.packaging.ConsumerPomTest.assertHasDependency(ConsumerPomTest.java:50)
	at org.eclipse.tycho.test.packaging.ConsumerPomTest.testReplaceP2(ConsumerPomTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

**Comment by mickaelistria** [comment]
@laeubi Do you have a clue? I can reproduce it locally, and with older commits as well, while the same commits have succeeded on CI ( https://ci.eclipse.org/tycho/job/tycho-github/job/master/33/ passes, if I check out this commit, `mvn clean install` it and run the CustomerPomTest, I see the same failure as CI...)
The log file tells about `[DEBUG] Cannot check /home/mistria/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.common/3.17.0.v20221108-1156/org.eclipse.equinox.common-3.17.0.v20221108-1156.jar from central because of kong.unirest.UnirestException: java.net.SocketTimeoutException: Read timed out`; so I suspect it's a network issue (or some quotas hit)?

**Comment by laeubi** [comment]
It might be that central is slow and probably there is also a user-limit, I'll see if we can maybe cache the search results in the local repo, but for the CI I think we always get a "fresh" copy.

**Comment by hd42** [comment]
We also noticed update-consumer-pom taking an inordinately long time in the last days. Maybe this could be further improved through parallelization and/or caching?

**Comment by hd42** [comment]
Maven Central seems to be very slow after multiple outages yesterday: https://status.maven.org/

Is there maybe a possibility to find artifacts in a local nexus (automatically recognized from settings.xml or as a configuration for Tycho) instead of maven central?

**Comment by mickaelistria** [comment]
> Is there maybe a possibility to find artifacts in a local nexus (automatically recognized from settings.xml or as a configuration for Tycho) instead of maven central?

I don't think this is implemented. Are you familiar with Nexus rest API? ie from a given URL, how can m2e determine it's a Nexus instance; and then query an artifact by its sha1 digest? If there is a simple enough solution to both, then m2e can probably add support for querying configured Nexus instances.

**Comment by laeubi** [comment]
Yes nexus has a search API as well, but it needs special config/implementation for Tycho as this one can't be decided from the `settings.xml`, if you like open a new issue and I can then start an implementation.

**Comment by laeubi** [comment]
The `4.0.0-SNAPSHOT` and `3.0.2-SNAPSHOT` will arrive in approximately an hour:

- https://ci.eclipse.org/tycho/job/tycho-github/job/master/
- https://ci.eclipse.org/tycho/job/tycho-github/job/tycho-3.0.x/

this should speedup things after the second run considerably.

**Comment by laeubi** [comment]
The fix for this issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com).

**Comment by laeubi** [comment]
The test still fails, because 
```
<dependency>
      <groupId>p2.eclipse.plugin</groupId>
      <artifactId>org.eclipse.equinox.registry</artifactId>
      <version>3.11.200.v20220817-1601</version>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>
```

can still not mapped ... I'll disable the test for now.

**Comment by laeubi** [comment]
The fix for this issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com).
