### ISSUE TITLE
P2 Repository access: Basic HTTP Auth breaks with version > 2.6

### ISSUE THREAD

**Issue by reuteran** [eclipse-tycho/tycho#2159]
I have been using tycho 1.4.0 to build our application, and want to upgrade to a newer version. We have our tagetplatform hosted in a p2 repository which we point our target definition file at. The repository accessible via HTTP and is protected by Basic HTTP Authentication. I have the credentials in my maven settings.xml, and I use maven 3.8.4.

When I run a tycho build with version 2.6 or lower, tycho can read the repository. However, there is an error where tycho can't resolve bundles that require OSGI Capabilities which are provided by bundles in the targetplatform, so I wanted to upgrade tycho to see if that can fix the issue.

However, if I use a tycho version of 2.7 or higher, and change nothing else, I will always get an authentication error:

> org.eclipse.equinox.p2.core.ProvisionException: Authentication failed for <my_repo>.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:200)
	at org.eclipse.tycho.p2.remote.RemoteRepositoryCacheManager.createCache(RemoteRepositoryCacheManager.java:69)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.getLocalFile(SimpleArtifactRepositoryFactory.java:68)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:92)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:80)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.factoryLoad(ArtifactRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:685)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:131)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:125)
	at org.eclipse.tycho.p2.remote.RemoteArtifactRepositoryManager.loadRepository(RemoteArtifactRepositoryManager.java:105)
	at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.loadRepository(RepositoryArtifactProvider.java:115)
	at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.getDelegate(LazyArtifactRepository.java:50)
	at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.contains(LazyArtifactRepository.java:87)
	at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.contains(RepositoryArtifactProvider.java:136)
	at org.eclipse.tycho.repository.local.MirroringArtifactProvider.isFileAlreadyAvailable(MirroringArtifactProvider.java:355)
	at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.lambda$0(CompositeArtifactProvider.java:171)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.isFileAlreadyAvailable(CompositeArtifactProvider.java:171)
	at org.eclipse.tycho.p2.target.TargetPlatformBaseImpl.isFileAlreadyAvailable(TargetPlatformBaseImpl.java:151)
	at org.eclipse.tycho.p2.target.PreliminaryTargetPlatformImpl.isFileAlreadyAvailable(PreliminaryTargetPlatformImpl.java:1)
	at org.eclipse.tycho.p2.resolver.DefaultP2ResolutionResult.lambda$0(DefaultP2ResolutionResult.java:55)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.tycho.p2.resolver.DefaultP2ResolutionResult.<init>(DefaultP2ResolutionResult.java:69)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.toResolutionResult(P2ResolverImpl.java:295)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:277)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveTargetDependencies(P2ResolverImpl.java:126)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:425)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:387)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:139)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0(TychoMavenLifecycleParticipant.java:157)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects(TychoMavenLifecycleParticipant.java:188)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:114)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:264)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

I have looked at the HTTP request in wireshark, and they do not have the HTTP Authorization header with the credentials. If I switch the version to 2.6 or lower, the Authorization header is added to subsequent request after the first request receives an 'Unauthorized' response. 

I could not find anything in the release notes for 2.7.

**Comment by laeubi** [comment]
@reuteran the current release of Tycho is 3.0.3 have you tried that out? 2.7.x is a bit outdated and did not receive latest updates anymore.

There are also some test-cases for this:
https://github.com/eclipse-tycho/tycho/blob/master/tycho-its/src/test/java/org/eclipse/tycho/test/target/PasswordProtectedP2RepositoryTest.java

So if you can enhance this testcase to show your error it would help.

**Comment by reuteran** [comment]
Hi @laeubi , thanks for the quick answer. Yes I have tried tycho 3.0.3 as well, with the same results. I will check out the test tomorrow and get it working and see if I can replicate the behavior.

**Comment by reuteran** [comment]
I found the problem:

When using tycho 1.4.0, I had not given my repositories in my target definition file an 'id' field, and for the server entry in the maven settings file simply justed the repository URI as the id. This doesn't seem to work anymore. I've now added an id field to my repositories in the target file and changed my settings.xml accordinly, and tycho 3.0.3 can now read the repository

**Comment by laeubi** [comment]
@reuteran actually if no ID given the full repository name should be used as a fallback, so if you can reproduce the problem it would be great to enhance the test-case to show the problem so we can fix it!

**Comment by reuteran** [comment]
@laeubi I'll see that I add that once I free up some time, shouldn't take too long
