### ISSUE TITLE
Does not have an expanded version error in m2e

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#2206]
Seen in a m2e builds

```
Description	Resource	Path	Location	Type
Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin {execution: default-package-plugin} (org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin:default-package-plugin:package)

org.eclipse.core.runtime.CoreException: Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin {execution: default-package-plugin}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$1(MavenBuilderImpl.java:139)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:122)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin failed: Project org.eclipse.m2e:org.eclipse.m2e.core:eclipse-plugin:2.0.7-SNAPSHOT does not have an expanded version
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
Caused by: java.lang.IllegalStateException: Project org.eclipse.m2e:org.eclipse.m2e.core:eclipse-plugin:2.0.7-SNAPSHOT does not have an expanded version
	at org.eclipse.tycho.core.osgitools.DefaultReactorProject.getExpandedVersion(DefaultReactorProject.java:247)
	at org.eclipse.tycho.packaging.PackagePluginMojo.getManifest(PackagePluginMojo.java:340)
	at org.eclipse.tycho.packaging.PackagePluginMojo.createPluginJar(PackagePluginMojo.java:275)
	at org.eclipse.tycho.packaging.PackagePluginMojo.execute(PackagePluginMojo.java:184)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 33 more
	pom.xml	/org.eclipse.m2e.core	line 15	Maven Build Problem

```

**Comment by laeubi** [comment]
The `build-qualifier` is actually executed, so probably the problem is caused by:
- https://github.com/eclipse-tycho/tycho/issues/2204

so first step should to to wait for the fix and then investigate if the problem remains.

**Comment by alexsuter** [comment]
I've the same problem. Do you have a solution for it?

**Comment by laeubi** [comment]
In my case the problem was that I have suppressed the execution of the mojo in the workspace preferences, so should should make sure that no Tycho mojos are disabled there:

![grafik](https://github.com/eclipse-tycho/tycho/assets/1331477/968a7c65-bd6e-438e-a45c-265161c9db65)

**Comment by travkin79** [comment]
Hi @laeubi,
I have the same issue with one of my projects (tycho version 4.0.8). In my project's lifecycle mappings I have the following.

<img width="427" height="197" alt="Image" src="https://github.com/user-attachments/assets/ed945e17-ce9d-4901-bf24-68c6842ebef9" />

What does source=extension mean in this case? Where can I check why the build-qualifier is ignored? There seems to be nothing special in the `pom.xml`:

```xml
...
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho.version}</version>
				<extensions>true</extensions>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>

...

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-packaging-plugin</artifactId>
					<version>${tycho.version}</version>
					<configuration>
						<format>yyyyMMdd-HHmm</format>
						<archive>
							<addMavenDescriptor>false</addMavenDescriptor>
						</archive>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
...
```

Though, I do have some lifecycle mapping filters activated in my workspace lifecycle meta-data (preferences). I created them because of some conflict.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
  <lifecycleMappingFilters>
    <lifecycleMappingFilter>
      <symbolicName>org.eclipse.m2e.pde.connector</symbolicName>
      <versionRange>[2.2.0,)</versionRange>
      <packagingTypes>
        <packagingType>eclipse-test-plugin</packagingType>
        <packagingType>eclipse-plugin</packagingType>
        <packagingType>eclipse-feature</packagingType>
      </packagingTypes>
    </lifecycleMappingFilter>
  </lifecycleMappingFilters>
</lifecycleMappingMetadata>
```

**Comment by laeubi** [comment]
Please check if any of the old "Tycho Connectors" is installed and unistal them.

**Comment by travkin79** [comment]
Where can I see and uninstall the installed tycho connectors and how can identify the "old tycho connectors"?

**Comment by laeubi** [comment]
Help > About Eclipse > Installation Details then search for Tycho

**Comment by travkin79** [comment]
Thank you, @laeubi. I have the following installed. It seems to be from 2022. But checking for updates doesn't find a newer version.

<img width="862" height="100" alt="Image" src="https://github.com/user-attachments/assets/a4d973d9-2347-41c9-aa35-e8940b0cb8d3" />

**Comment by salvatore-coppola** [comment]
> Thank you, [@laeubi](https://github.com/laeubi). I have the following installed. It seems to be from 2022. But checking for updates doesn't find a newer version.
> <img alt="Image" width="862" height="100" src="https://private-user-images.githubusercontent.com/10887297/467092679-a4d973d9-2347-41c9-aa35-e8940b0cb8d3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMxMjYwOTMsIm5iZiI6MTc2MzEyNTc5MywicGF0aCI6Ii8xMDg4NzI5Ny80NjcwOTI2NzktYTRkOTczZDktMjM0Ny00MWM5LWFhMzUtZTg5NDBiMGNiOGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE0VDEzMDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZDJkOWExNWUwYmYxZGEwODRiODY5MzY2YzMwYzBmYmI4YzM1YzgxYjJkOWQ1NGFlODE2ZmRhOWNiN2I0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PtCbHJE1h0vCn-_lssM7XLHCaAwYBEX1JjamzJwAxvg">

removing that plugin fixed the problem for me
