### ISSUE TITLE
Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin {execution: default-package-plugin}

### ISSUE THREAD

**Issue by laeubi** [eclipse-tycho/tycho#2581]
```
Description	Resource	Path	Location	Type
Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin {execution: default-package-plugin} (org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin:default-package-plugin:package)

org.eclipse.core.runtime.CoreException: Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin {execution: default-package-plugin}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$1(MavenBuilderImpl.java:139)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:122)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:package-plugin failed: Project org.eclipse.m2e:org.eclipse.m2e.editor.lemminx:eclipse-plugin:2.0.4-SNAPSHOT does not have an expanded version
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
Caused by: java.lang.IllegalStateException: Project org.eclipse.m2e:org.eclipse.m2e.editor.lemminx:eclipse-plugin:2.0.4-SNAPSHOT does not have an expanded version
	at org.eclipse.tycho.core.osgitools.DefaultReactorProject.getExpandedVersion(DefaultReactorProject.java:247)
	at org.eclipse.tycho.packaging.PackagePluginMojo.getManifest(PackagePluginMojo.java:340)
	at org.eclipse.tycho.packaging.PackagePluginMojo.createPluginJar(PackagePluginMojo.java:275)
	at org.eclipse.tycho.packaging.PackagePluginMojo.execute(PackagePluginMojo.java:184)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	... 33 more
	pom.xml	/org.eclipse.m2e.editor.lemminx	line 59	Maven Build Problem

```

**Comment by sebthom** [comment]
I am seeing the same error in Eclipse 2023-06 for all plugin projects where I upgraded from tycho 3 to 4.0.0. What does `Caused by: java.lang.IllegalStateException: Project XYZ does not have an expanded version` mean and how can it be solved?

**Comment by laeubi** [comment]
@sebthom in m2eclipse mojos are only executed on a very small project subset so Tycho needs to be less strict in this regard, so usually there is something (not yet) there but Tycho has a hard assert. This must be solved by Tycho, if you where able to reduce it to a small project it would be great to [contribute this to m2e as a testcase](https://github.com/eclipse-m2e/m2e-core) so we can make sure it is really fixed afterwards.

**Comment by laeubi** [comment]
@sebthom It seems this can happen if the `build-qualifier` mojo is not executed, can you check in the Mapping View if the mojo is listed there?

**Comment by sebthom** [comment]
yes, the execution of the build-qualifier goal was ignored:
![image](https://github.com/eclipse-tycho/tycho/assets/426959/224dc0a3-9ddf-4ed5-bf3c-73d33c156a59)

I changed the lifecycle-mapping to execute it, now the error is gone.

**Comment by laeubi** [comment]
At least for the problematic project I found this error it is ignored:

![grafik](https://github.com/eclipse-tycho/tycho/assets/1331477/2681e574-6137-425e-858d-b7b2ce71a67c)

@HannesWell do you have an idea? The metadata at Tycho looks fine and the package mojo is executed, so the question is why the `build-qualifier` is ignored?!?

**Comment by sebthom** [comment]
In my case it was ignored via a parent pom:

```xml
      <pluginManagement>
         <plugins>
            <plugin>
               <groupId>org.eclipse.m2e</groupId>
               <artifactId>lifecycle-mapping</artifactId>
               <version>1.0.0</version>
               <configuration>
                  <lifecycleMappingMetadata>
                     <pluginExecutions>
                        <pluginExecution>
                           <pluginExecutionFilter>
                              <groupId>org.eclipse.tycho</groupId>
                              <artifactId>tycho-packaging-plugin</artifactId>
                              <versionRange>[1.0,)</versionRange>
                              <goals>
                                 <goal>build-qualifier</goal>
                                 <goal>build-qualifier-aggregator</goal>
                                 <goal>validate-id</goal>
                                 <goal>validate-version</goal>
                              </goals>
                           </pluginExecutionFilter>
                           <action>
                              <ignore />
                           </action>
                        </pluginExecution>
                     </pluginExecutions>
                  </lifecycleMappingMetadata>
               </configuration>
            </plugin>
         </plugins>
```

I can't remember why I put it there in the beginning. Maybe it was best practice at a time?

**Comment by laeubi** [comment]
So it does it work if you remove the ignore?

**Comment by sebthom** [comment]
Yes.

**Comment by laeubi** [comment]
Did it show the source as pom for the ignore? Because in my screenshot from m2e-core it shows "unknown" as the source and I can't find any direct ignores ...

**Comment by laeubi** [comment]
Okay for me it was ignored in the workspace preferences, so I think we can close this here as it is/was a configuration error and not a general Tycho issue!

**Comment by alexsuter** [comment]
Same issue here. I also had those goals on ignore. If you was an early tycho user, then you may have those ignores in your pom files.

Now it is working.
