### ISSUE TITLE
Clarification on recommended setup for JUnit 5

### ISSUE THREAD

**Issue by tivervac** [eclipse-tycho/tycho#2665]
[This page](https://wiki.eclipse.org/Tycho/How_Tos/JUnit5) seems rather old. The recommended way in this article is to add the JUnit 5 container and use Import-Package instead of Required-Bundle (though it doesn't mention why). I'm wondering whether it's still the recommended way of configuring your project for JUnit 5. 

For context:

We're in the progress of updating our product (both development and RCP target) to 2023-03 from 2022-03 (yes we're very late to the party). In the past, tests always ran fine on the command line via Tycho, and could be started and finished cleanly from within Eclipse (Run As > JUnit (Plug in) Test). After having upgraded, we ran into the issue where we couldn't get a project setup where both Tycho and JUnit Plugin tests in Eclipse were green.

The migration is now basically done and both Tycho and Eclipse Plugin Tests are green. We've achieved this by moving from Require-Bundle for `org.junit.jupiter` and `org.junit.platform` to import-package and getting rid of our `pomDependencies=consider`. We've not added the JUnit 5 containers to any of our projects as those caused more harm than good.

Sadly, having reached the end, we only just noticed that Eclipse JUnit plugin tests fail on Windows, while being green on Linux and mac. Regular Eclipse JUnit tests as well as Tycho tests work fine on all platforms.

I do realize that this seems more of an Eclipse/JDT/PDE? error than a Tycho one, but Tycho is the only one that has _any_ documentation on the matter, thus here I am. Seeing that you have the documentation, and need to correctly handle junit integration, I also suspect you might have more knowledge on how JUnit is supposed to be handled in an Eclipse environment.

I'm trying to run a JUnit plugin test for one of our most basic plugins and get the following error (this is the same error we got on linux before using import package).

```
!ENTRY org.eclipse.ui 4 0 2023-07-27 11:59:02.081
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Bundle "org.eclipse.jdt.junit5.runtime" not found. Possible causes include missing dependencies, too restrictive version ranges, or a non-matching required execution environment.
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.getClassLoader(RemotePluginTestRunner.java:123)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.readPluginArgs(RemotePluginTestRunner.java:173)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.init(RemotePluginTestRunner.java:130)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:67)
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$1(E4Testable.java:127)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:53)
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:47)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

Our manifest looks like this
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: com.sigasi.hdt.epl.ui.test
Bundle-SymbolicName: com.sigasi.hdt.epl.ui.test
Bundle-Version: 5.3.0.qualifier
Bundle-Vendor: Sigasi
Bundle-RequiredExecutionEnvironment: JavaSE-17
Require-Bundle: com.google.guava;bundle-version="[30.1.0,31.0.0)",
 com.sigasi.hdt.epl.ui;bundle-version="[5.3.0,5.3.1)",
 com.sigasi.hdt.epl;bundle-version="[5.3.0,5.3.1)",
 com.sigasi.hdt.epl.test;bundle-version="[5.3.0,5.3.1)",
 org.eclipse.xtext.testing;bundle-version="[2.29.0,2.30.0)",
 org.eclipse.xtext.ui.shared;bundle-version="[2.29.0,2.30.0)",
 org.eclipse.xtext.ui.testing;bundle-version="[2.29.0,2.30.0)",
 org.eclipse.lsp4j;bundle-version="[0.19.0,0.20.0)"
Bundle-ActivationPolicy: lazy
Automatic-Module-Name: com.sigasi.hdt.epl.ui.test
Import-Package: org.apache.log4j,
 org.junit.jupiter.api;version="[5.9.2,6)",
 org.junit.jupiter.api.function;version="[5.9.2,6)",
 org.junit.jupiter.api.condition;version="[5.9.2,6)",
 org.junit.platform.commons;version="[1.9.2,2)",
 org.junit.platform.engine;version="[1.9.2,2)"
Export-Package: com.sigasi.hdt.epl.ui.test.testing;uses:="org.eclipse.ui"
```

And the classpath as follows

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins">
	</classpathentry>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

All of this using Tycho 3.0.5

**Comment by laeubi** [comment]
For Tycho 4+ (!) the documentation for Tycho is here (while most of it also applies to Tycho 3):

https://tycho.eclipseprojects.io/doc/4.0.0/TestingBundles.html

There are also some recent fixes regarding JUnit support in Tycho 4.0.1-SNAPSHOT but these are mostly for details.

Please note that there are considerable differences between `JUnit Tests` (that don't run inside OSGi container by default) and `JUnit Plugin Tests` both in Tycho and PDE and you probably need to adjust for recent changes in the target platform. For me it is not quite clear if the test fails on Tycho or PDE, if it fails on PDE you should [report it here](https://github.com/eclipse-pde/eclipse.pde), because Tycho can't do much in this regards.

**Comment by tivervac** [comment]
Thanks for the extra link, I hadn't found that yet. The issue indeed doesn't lie with Tycho but rather PDe, so thanks for that link I'll crosspost there. The Tycho 4 document link doesn't mention anything about the JUnit 5 container nor import package-ing junit dependencies. Do you know anything more about this? As it seems that when we add JUnit 5 containers, or use require bundle, the tests fail in a tycho setup.

**Comment by tivervac** [comment]
Alright, thanks. I've opened this ticket [instead ](https://github.com/eclipse-pde/eclipse.pde/issues/682).
