### ISSUE TITLE
Default lifecycle mapping for tycho packaging produces exception for bundles with nested jars

### ISSUE THREAD

**Issue by jstroleny** [eclipse-tycho/tycho#2858]
Use following its project [sourceBundle.nestedJars](https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/sourceBundle.nestedJars) and import it into Eclipse and enable Maven nature to it.

This bundle uses multiple nested jars as output, each have its own `nameOfJar-classes` directory in `target` folder.
When imported into Eclipse with Maven nature enabled, it causes errors (maven build problem, see below).

When bundle with single jar is imported with same steps (e.g. [packaging.consumer.pom](https://github.com/eclipse-tycho/tycho/tree/master/tycho-its/projects/packaging.consumer.pom/bundle)) there is no error.

```
Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.2:package-plugin {execution: default-package-plugin} (org.eclipse.tycho:tycho-packaging-plugin:4.0.2:package-plugin:default-package-plugin:package)

org.eclipse.core.runtime.CoreException: Failed to execute mojo org.eclipse.tycho:tycho-packaging-plugin:4.0.2:package-plugin {execution: default-package-plugin}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$2(MavenBuilderImpl.java:153)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:133)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not create jar bar.jar
	at org.eclipse.tycho.packaging.PackagePluginMojo.makeJar(PackagePluginMojo.java:217)
	at org.eclipse.tycho.packaging.PackagePluginMojo.createSubJars(PackagePluginMojo.java:191)
	at org.eclipse.tycho.packaging.PackagePluginMojo.execute(PackagePluginMojo.java:182)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: /git/example/sourceBundle.nestedJars/target/bar.jar-classes isn't a directory.
	at org.codehaus.plexus.archiver.AbstractArchiver.addFileSet(AbstractArchiver.java:324)
	at org.codehaus.plexus.archiver.AbstractArchiver.addDirectory(AbstractArchiver.java:288)
	at org.eclipse.tycho.packaging.PackagePluginMojo.makeJar(PackagePluginMojo.java:204)
	... 36 more
```

**Comment by laeubi** [comment]
@jstroleny this seems quite easy to fix by make sure the `PackagePluginMojo.makeJar` check if the folder actually exits (and create it if not). Do you like to propose a PR for this?

We plan to release a new Tycho bugfix release and this seems good to be included!
