### ISSUE TITLE
Doesn't work in NetBeans

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-tycho/tycho#2970]
I'm having fun trying to use NetBeans LS in Eclipse IDE, and I wanted to try it on Eclipse plugin projects (without Eclipse PDE).
But Netbeans is unhappy
```
Project /home/mistria/git/eclipse.platform.ui/tools: Error reading project model: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: OutOfScopeException: Cannot access session scope outside of a scoping block
  at SessionScopeModule.configure(SessionScopeModule.java:55)
      \\_ installed by: WireModule -\u003e SessionScopeModule
  at TychoProjectManager.(TychoProjectManager.java:80)
      \\_ for 1st parameter
  at ClassRealm[extension\u003eorg.eclipse.tycho:tycho-maven-plugin:4.0.4-SNAPSHOT, parent: ModuleCL@6996b7f6[org.netbeans.modules.maven.embedder]]
      \\_ installed by: WireModule -\u003e PlexusBindingModule
  while locating TychoProjectManager
  while locating P2DependencyResolver
  at ClassRealm[extension\u003eorg.eclipse.tycho:tycho-maven-plugin:4.0.4-SNAPSHOT, parent: ModuleCL@6996b7f6[org.netbeans.modules.maven.embedder]]
      \\_ installed by: WireModule -\u003e PlexusBindingModule
  while locating DependencyResolver annotated with @Named("p2")
  while locating DefaultTychoResolver
  at ClassRealm[extension\u003eorg.eclipse.tycho:tycho-maven-plugin:4.0.4-SNAPSHOT, parent: ModuleCL@6996b7f6[org.netbeans.modules.maven.embedder]]
      \\_ installed by: WireModule -\u003e PlexusBindingModule
  while locating TychoResolver
  while locating TychoMavenLifecycleParticipant
  at ClassRealm[extension\u003eorg.eclipse.tycho:tycho-maven-plugin:4.0.4-SNAPSHOT, parent: ModuleCL@6996b7f6[org.netbeans.modules.maven.embedder]]
      \\_ installed by: WireModule -\u003e PlexusBindingModule
  while locating AbstractMavenLifecycleParticipant annotated with @Named("TychoMavenLifecycleListener")

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
AbstractMavenLifecycleParticipant: "org.apache.maven.AbstractMavenLifecycleParticipant"
DefaultTychoResolver:              "org.eclipse.tycho.core.resolver.DefaultTychoResolver"
DependencyResolver:                "org.eclipse.tycho.core.DependencyResolver"
Named:                             "com.google.inject.name.Named"
OutOfScopeException:               "com.google.inject.OutOfScopeException"
P2DependencyResolver:              "org.eclipse.tycho.p2resolver.P2DependencyResolver"
PlexusBindingModule:               "org.eclipse.sisu.plexus.PlexusBindingModule"
SessionScopeModule:                "org.apache.maven.session.scope.internal.SessionScopeModule"
TychoMavenLifecycleParticipant:    "org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant"
TychoProjectManager:               "org.eclipse.tycho.core.TychoProjectManager"
TychoResolver:                     "org.eclipse.tycho.resolver.TychoResolver"
WireModule:                        "org.eclipse.sisu.wire.WireModule"
========================
End of classname legend:
========================
```

Is there anything easy enough for a quick try I can do on my end or Tycho end to hopefully make it work?

**Comment by laeubi** [comment]
It seems Netbeans is working differently than maven here and does not init the session before invoking extensions, I fear there is not much one can do from plugin side.

**Comment by mickaelistria** [comment]
OK, thanks for the hint, I'll try to keep it in mind. Let's close here.
