### ISSUE TITLE
tycho-p2-extras-plugin: Mirroring of an old style update site fails with Tycho 4.0.6

### ISSUE THREAD

**Issue by howlger** [eclipse-tycho/tycho#3701]
I use  the `tycho-p2-extras-plugin` to convert an old style update site into a p2 update site by first mirroring it, removing the metadata and then recreating the metadata (see [here](https://github.com/howlger/IDEalized/blob/master/mirror-non-p2/pom.xml)). But **mirroring of an old style update site** with the `tycho-p2-extras-plugin` **fails in Tycho 4.0.6** and 4.0.0. In contrast, it worked in Tycho 3.0.5.

Error message (Tycho 4.0.6):
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.6:mirror (mirror-update-sites) on project non-p2_update_sites: Error during mirroring: Mirroring failed: The p2 repository at https://zipeditor.sourceforge.net/update contains partial IUs (see above) from an old style update site which cannot be used for dependency resolution -> [Help 1]
```

Tycho 4.0.6 gives only the error message above, while Tycho 4.0.5 gives also the following stack trace:
```
[2f5dae42-67fb-4513-9698-db8eb13d1865][plugin>org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.5] Provisioning exception
org.eclipse.equinox.p2.core.ProvisionException: The p2 repository at https://zipeditor.sourceforge.net/update contains partial IUs (see above) from an old style update site which cannot be used for dependency resolution
	at org.eclipse.tycho.p2maven.transport.RemoteMetadataRepositoryManager.failIfRepositoryContainsPartialIUs(RemoteMetadataRepositoryManager.java:89)
	at org.eclipse.tycho.p2maven.transport.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:69)
	at org.eclipse.tycho.p2maven.transport.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:59)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:161)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:188)
	at org.eclipse.tycho.p2tools.copiedfromp2.AbstractApplication.getCompositeMetadataRepository(AbstractApplication.java:258)
	at org.eclipse.tycho.p2tools.MirrorApplicationServiceImpl.mirrorStandalone(MirrorApplicationServiceImpl.java:111)
	at org.eclipse.tycho.plugins.p2.extras.MirrorMojo.execute(MirrorMojo.java:252)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
```

The test [`testMirrorFromOldStyleUpdatesite()` has been removed](https://github.com/eclipse-tycho/tycho/commit/d32372094adb61c80b329512f92c5cb3e80d6418#diff-ad2feeca05fc32c5bec3dcaaf95f31ee978d190624406ab4a87b7677d6533f41) some time ago while the [test resources are still there](https://github.com/eclipse-tycho/tycho/tree/main/tycho-extras/tycho-p2-extras-plugin/src/test/resources/mirroring/sourceUpdatesite), but seem to be unused.

Is it intentional that Tycho 4.x no longer supports the mirroring of old style update sites? And if so, how can old style update sites be converted into p2 update sites in Tycho 4.x?

**Comment by laeubi** [comment]
@howlger do you have access to the old site? If you can download it somehow you should be able to use the [publish-features-and-bundles](https://tycho.eclipseprojects.io/doc/latest/tycho-extras/tycho-p2-extras-plugin/publish-features-and-bundles-mojo.html) to generate an update site from a folder of bundles and features.

**Comment by howlger** [comment]
> @howlger do you have access to the old site? If you can download it somehow you should be able to use the [publish-features-and-bundles](https://tycho.eclipseprojects.io/doc/latest/tycho-extras/tycho-p2-extras-plugin/publish-features-and-bundles-mojo.html) to generate an update site from a folder of bundles and features.

Thank you for the quick response.

Yes, I have access to the old site and I'm also using `publish-features-and-bundles` to generate the p2 metadata for the old update site. I'm following [the Tycho example in the Eclipse Wiki](https://wiki.eclipse.org/Tycho/Additional_Tools#publish-features-and-bundles_goal) using the **`mirror` goal** (step 1) **to get the old site** which no longer works in 4.x.

**Comment by laeubi** [comment]
So I think then best would then to download the site via FTP, generate the new metadata with `publish-features-and-bundles` and upload the new metadata (it should be enough p2.index + content/artifacts.jar/xz file).

**Comment by howlger** [comment]
So Tycho 4.x no longer supports the mirroring of old-style update sites, right?

If yes,
- this issue can be closed and
- [the sample old-style update site for testing mirroring](https://github.com/eclipse-tycho/tycho/tree/main/tycho-extras/tycho-p2-extras-plugin/src/test/resources/mirroring/sourceUpdatesite) can be removed from the code (should I provide a pull request for that?).

For mirroring, I'm going to stick with Tycho 3.0.5 for now and I'm considering helping the projects providing old-style update sites I'm consuming to migrate to p2.

**Comment by laeubi** [comment]
@howlger it seems to be the case, maybe one can enable this somehow for the mirror goal but no one has actually looked into this as it seems for a long time now and also the wiki content was not migrated yet so it looks like something people not doing very often.

So if you want to give it a try to recover the feature and documentation that would also be an option, today it is much easier as Tycho can directly call P2 code from maven.

**Comment by howlger** [comment]
The only use case I know of is converting an old-style update site from someone else to use it in a Tycho build and for that Tycho 3.0.5 works fine. If I find time, I would like to work on other things (e.g. to create a flat update site that can be published on GitHub as assets of a release).

**Comment by howlger** [comment]
I added it to the FAQ here: https://github.com/eclipse-tycho/tycho/wiki/Frequently-asked-questions#how-to-convert-an-old-style-update-site-with-a-sitexml-file-into-a-p2-update-site

**Comment by laeubi** [comment]
Thanks, do you think we can close this issue now its documented?

**Comment by howlger** [comment]
Yes, thanks for all your prompt replies and inputs.

Please review the [FAQ](https://github.com/eclipse-tycho/tycho/wiki/Frequently-asked-questions) for the following changes I made in addition to adding the documentation for this issue:
- Rewording of some existing headings which unfortunately leads to different anchors (as far as I know, it is not possible to set an ID for a heading)
- Using [collapsed sections](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections#creating-a-collapsed-section) for the answers (unfortunately, the question/heading itself cannot be made expandable because Markdown cannot be used in the summary element)
