### ISSUE TITLE
UTF-8 BOM plus xml decl of ISO-8859-1 is incompatible

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-tycho/tycho#4073]
We sometimes see errors like below in our builds:

```
[WARNING] The POM for org.apache.commons:commons-lang3:jar:3.14.0 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.apache.commons:commons-lang3:3.14.0
[FATAL] Non-parseable POM C:\Users\Jenkins\.m2\repository\org\apache\commons\commons-parent\64\commons-parent-64.pom: UTF-8 BOM plus xml decl of ISO-8859-1 is incompatible (position: START_DOCUMENT seen <?xml version="1.0" encoding="ISO-8859-1"... @1:42)  @ C:\Users\Jenkins\.m2\repository\org\apache\commons\commons-parent\64\commons-parent-64.pom, line 1, column 42
```
They happen if a pom.xml is read with incorrect encoding, because the implementation _assumes_ a certain encoding, and the file doesn't fit to that assumption.

The good news: Many other projects have run into this before, so there are fixes readily available:
https://github.com/jaredsburrows/gradle-license-plugin/pull/291
https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/152

I suggest to use the same approach: Replace all the FileReaders (or other Java runtime based Readers) on pom.xml files with `ReaderFactory.newXmlReader()`, as that one can detect the used encoding, thereby avoiding the exception.

**Comment by laeubi** [comment]
I think this is a "maven error" an nothing Tycho can adjust.

**Comment by Bananeweizen** [comment]
Unfortunately I have to look for a reproducer again at work, but the root cause is code like https://github.com/eclipse-tycho/tycho/blob/main/tycho-extras/tycho-pomless/src/main/java/org/eclipse/tycho/pomless/AbstractTychoMapping.java#L126, which hardcodes the encoding of the newly created FileReader to UTF-8, and that pre-configured encoding then conflicts with the actual encoding in the XML file for the POM. It's not about BOMs in files at all. The referenced other project issues basically refactored their (similar hardcoded) code to use a plexus utility class which doesn't have a hardcoded encoding, but which rather looks it up when reading the XML.

**Comment by merks** [comment]
That would explain why I only had problems with iso-latin encoded files and it was fixed by converting them to UTF-8 encoding!

**Comment by laeubi** [comment]
@Bananeweizen I can't see how the mentioned line contributes to the problem?

1. It is not using the plexus-xml reader (what is the one to blame here)
2. It is not reading only XML files and determines the charset based on file-type
3. It is never reading any dependency (e.g. pom files)

So this could only be an issue for the insane case that someone uses a `feature.xml`, `category.xml` or `*.product` file not using the default UTF-8 encoding (what only can be archived by manually editing this files) and I'm not sure this is something I want to see supported for Tycho anyways...

**Comment by merks** [comment]
Good idea about the `-X` thing!  I will try to reproduce the problem again today and gather more details...

**Comment by Bananeweizen** [comment]
@laeubi I believe there are multiple wrong assumptions on your side:
* This is about Maven `pom.xml`s of third party libraries used in a target platform, not about native P2 files, like feature.xml.
* Those *are* encoded in different encodings and that's perfectly fine: 
![grafik](https://github.com/user-attachments/assets/bc1c8a1e-7330-4789-a8b1-b55cde407448)
* The plexus XML reader factory is the _solution_, not the problem.

Regarding reproducing: I have a target containing such a commons lang3 artifact, but I still don't get the warning, even after deleting the related org/apache/commons paths in my local m2 repo. Do I need to clean some other caching location to enforce a fresh download during target platform resolution?

**Comment by laeubi** [comment]
> This is about Maven pom.xmls of third party libraries used in a target platform, not about native P2 files, like feature.xml.

Your referenced code in Tycho has nothing to do with target resolution at all so I think in general my assumption is correct that is unlikely the source of the problem.

> Regarding reproducing: I have a target containing such a commons lang3 artifact, but I still don't get the warning, even after deleting the related org/apache/commons paths in my local m2 repo. Do I need to clean some other caching location to enforce a fresh download during target platform resolution?

If you want to be 100% sure the only clean way is use a clean m2 repo e.g. with `-Dmaven.repo.local=/tmp/testme`

**Comment by merks** [comment]
Here is a stack trace for the failure during my build via m2e launcher:
```
[ERROR] Plugin org.codehaus.mojo:build-helper-maven-plugin:3.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:build-helper-maven-plugin:jar:3.3.0: 1 problem was encountered while building the effective model
[ERROR] [FATAL] Non-parseable POM D:\Users\actico-3\.m2\repository\org\codehaus\mojo\build-helper-maven-plugin\3.3.0\build-helper-maven-plugin-3.3.0.pom: UTF-8 BOM plus xml decl of ISO-8859-1 is incompatible (position: START_DOCUMENT seen <?xml version="1.0" encoding="ISO-8859-1"... @1:42)  @ line 1, column 42
[ERROR] -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.codehaus.mojo:build-helper-maven-plugin:3.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:build-helper-maven-plugin:jar:3.3.0
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:132)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.lambda$getPluginDescriptor$0(DefaultMavenPluginManager.java:183)
	at org.apache.maven.plugin.DefaultPluginDescriptorCache.lambda$get$0(DefaultPluginDescriptorCache.java:72)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.maven.plugin.DefaultPluginDescriptorCache.get(DefaultPluginDescriptorCache.java:70)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:181)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:271)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:214)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecution(DefaultLifecycleExecutionPlanCalculator.java:155)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:143)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:122)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:135)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:93)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:100)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.codehaus.mojo:build-helper-maven-plugin:jar:3.3.0
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:294)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:172)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:268)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:107)
	... 30 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM D:\Users\actico-3\.m2\repository\org\codehaus\mojo\build-helper-maven-plugin\3.3.0\build-helper-maven-plugin-3.3.0.pom: UTF-8 BOM plus xml decl of ISO-8859-1 is incompatible (position: START_DOCUMENT seen <?xml version="1.0" encoding="ISO-8859-1"... @1:42)  @ line 1, column 42

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:176)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:586)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:257)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
	... 33 more
```

**Comment by laeubi** [comment]
By the way this can heavily depend on maven+tycho version so at best mention these for a related stack trace as well.
Also there is a new version for buildhelper: https://mvnrepository.com/artifact/org.codehaus.mojo/build-helper-maven-plugin/3.6.0

**Comment by akurtakov** [comment]
Last couple of comments reminded me of https://github.com/mojohaus/build-helper-maven-plugin/issues/168 and I'm almost 100% sure this is what you face.

**Comment by merks** [comment]
@akurtakov 

Indeed, the 3.3.0 was hard coded in one of the pom.xml files!  Thanks!!

**Comment by ffays** [comment]
Quick fix for `[FATAL] Non-parseable POM` : replace all `'<?xml version="1.0" encoding="ISO-8859-1"?>` with `<?xml version="1.0"?>` from POM files in your local Maven repository:

```sh
# Windows (Powershell)
Get-ChildItem -Recurse $HOME\.m2\repository\*.pom | ? { Select-String -Pattern '<?xml version="1.0" encoding="ISO-8859-1"?>' -SimpleMatch -List -Path $_ } | % { (Get-Content $_) -ireplace [regex]::Escape('<?xml version="1.0" encoding="ISO-8859-1"?>'), '<?xml version="1.0"?>' | Set-Content $_ }

# Linux
find $HOME/.m2/repository -type f -name '*.pom' -exec grep -li '<?xml version="1.0" encoding="ISO-8859-1"?>' {} \; | xargs sed -i '1 s|<?xml version="1.0" encoding="ISO-8859-1"?>|<?xml version="1.0"?>|i'

# Mac OS
find $HOME/.m2/repository -type f -name '*.pom' -exec grep -li '<?xml version="1.0" encoding="ISO-8859-1"?>' {} \; | xargs sed -i '' '1 s|<?xml version="1.0" encoding="ISO-8859-1"?>|<?xml version="1.0"?>|i'
```
